
#The compilation command (Note: The indentation below MUST be a literal Tab character)
#For local windows hosting ensure outfile is .exe and no need to run mkdir
Default: src/*.cpp
	mkdir -p build
	g++ src/*.cpp -o build/dataStructure